[package]
name = "polynomial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "polynomial"
path = "src/lib.rs"

[dependencies]
logos="0.13.0"
regex="1.10.2"
num="0.4.1"
